# Generated by Django 5.1.3 on 2024-12-12 01:22

import appRecipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appRecipe", "0002_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default="category/default.jpg",
                null=True,
                upload_to=appRecipe.models.Category.get_file_path,
            ),
        ),
    ]
